# aws_ec2.yml

plugin: aws_ec2
regions:
  - us-east-1 # CONFIRMADO por la prueba de la CLI

keyed_groups:
  - key: tags.Role
    prefix: role
hostnames:
  - tag:Name
  - public-ip-address 

# Asigna la IP privada como la variable ansible_host
compose:
  ansible_host: public_ip_address
filters:
  instance-state-name: running
  tag:Name: "pf-*"
